site_name: My Docs
pages:
  - Home: index.md
  - Grid-tools: grid-tools.md
  - Testing framework: 
        - Serialbox: serialbox.md
        - Verification framework: dwarfs.md
        - Advanced debugging: debuging.md
  - Colaboration framework:
        - Git & git flow: git-flow.md
        - Open project: openproject.md
  - Tools:
        - cmake: cmake.md
        - slack: slack.md
        - jenkins: jenkins.md
  - General tips: misc.md
theme: readthedocs
